# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/msm8226-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/msm8226-common/proprietary/system/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/samsung/msm8226-common/proprietary/system/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/samsung/msm8226-common/proprietary/system/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/samsung/msm8226-common/proprietary/system/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/libaptX_encoder.so:system/vendor/lib/libaptX_encoder.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/libloc_api_v02.so:system/vendor/lib/libloc_api_v02.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/libloc_ds_api.so:system/vendor/lib/libloc_ds_api.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/libstlport.so:system/vendor/lib/libstlport.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/msm8226-common/proprietary/system/vendor/bin/lpm:system/vendor/bin/lpm \
    vendor/samsung/msm8226-common/proprietary/system/vendor/bin/charger_monitor:system/vendor/bin/charger_monitor
